name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 5.0.x
        - run: |
            dotnet publish src/NaCLI/NaCLI.csproj --self-contained -r win-x64 -o publish/win-x64
            dotnet publish src/NaCLI/NaCLI.csproj --self-contained -r win-x86 -o publish/win-x86
            dotnet publish src/NaCLI/NaCLI.csproj --self-contained -r win7-x64 -o publish/win7-x64
            dotnet publish src/NaCLI/NaCLI.csproj --self-contained -r win7-x86 -o publish/win7-x86
